### ISSUE TITLE
How to Use?

### ISSUE THREAD

**Issue by xYamiDx** [sindresorhus/taskkill#2]
Hello,

I am new to this, I have a normal application in php but I need to use this application to kill client-side applications.

As I can add to my app?
I do not understand terms "$ npm install --save taskkill"

Thank you

**Comment by sindresorhus** [comment]
This is a [Node.js module](https://nodejs.org/en). [npm](https://npmjs.org/) is the package manager. To  kill a process from PHP, check out [fkill-cli](https://github.com/sindresorhus/fkill-cli) instead which you can easily [spawn](http://stackoverflow.com/questions/8956732/php-spawn-process).

**Comment by shinnn** [comment]
@xYamiDx Also, [fkill-cli](https://github.com/sindresorhus/fkill-cli) is easier to use with [`exec`](http://php.net/manual/function.exec.php).
